// SPDX-License-Identifier: MIT
// Copyright (c) 2026 The Bento authors
//
// GENERATED by scripts/build-modelkeys.mjs from slides/src/model.ts — do not
// edit. Run `node scripts/build-modelkeys.mjs` after changing the format's
// interfaces; CI fails if this file is out of date.
//
// The property names the bento/slides format defines. `validate()` reports
// anything outside these sets, because an unknown key is ignored silently and
// a typo just means the styling does not apply.

export const MODEL_KEYS = {
    "doc": ["assets", "blobs", "collab", "docId", "fonts", "format", "layouts", "meta", "modified", "present", "readonly", "size", "slides", "template", "theme", "title", "version"],
    "slide": ["background", "comments", "elements", "hidden", "hover", "id", "name", "notes", "stateOf", "themeRefs", "transition", "unnumbered"],
    "comment": ["at", "author", "elementId", "id", "replies", "resolved", "text", "x", "y"],
    "element": {
      "text": ["align", "backdropFilter", "blend", "blur", "color", "colorGradient", "fontFamily", "fontSize", "fontWeight", "fx", "group", "groupId", "h", "html", "id", "letterSpacing", "lineHeight", "link", "morphId", "opacity", "placeholder", "role", "rotation", "shadow", "showOnHover", "textStroke", "themeRefs", "type", "valign", "w", "x", "y"],
      "shape": ["backdropFilter", "blend", "blur", "d", "fill", "fillGradient", "from", "fx", "group", "groupId", "h", "heads", "id", "lineEnd", "lineStart", "link", "morphId", "opacity", "pathBox", "radius", "role", "rotation", "shadow", "shape", "showOnHover", "stroke", "strokeDash", "strokeStyle", "strokeWidth", "themeRefs", "to", "type", "w", "x", "y"],
      "image": ["backdropFilter", "blend", "blur", "crop", "fit", "fx", "group", "groupId", "h", "id", "keepAspectRatio", "link", "morphId", "opacity", "radius", "role", "rotation", "shadow", "showOnHover", "src", "themeRefs", "type", "w", "x", "y"],
      "svg": ["asset", "backdropFilter", "blend", "blur", "css", "fx", "group", "groupId", "h", "id", "link", "markup", "morphId", "opacity", "role", "rotation", "shadow", "showOnHover", "themeRefs", "type", "w", "x", "y"],
      "chart": ["backdropFilter", "blend", "blur", "fx", "group", "groupId", "h", "id", "link", "morphId", "opacity", "option", "preset", "role", "rotation", "shadow", "showOnHover", "source", "themeRefs", "type", "w", "x", "y"],
      "table": ["backdropFilter", "blend", "blur", "columns", "fx", "group", "groupId", "h", "header", "id", "link", "morphId", "opacity", "role", "rotation", "rows", "shadow", "showOnHover", "style", "themeRefs", "type", "w", "x", "y"],
      "media": ["autoplay", "backdropFilter", "blend", "blur", "controls", "fit", "fx", "group", "groupId", "h", "id", "kind", "link", "loop", "morphId", "muted", "opacity", "poster", "radius", "role", "rotation", "shadow", "showOnHover", "src", "themeRefs", "type", "w", "x", "y"],
      "embed": ["app", "backdropFilter", "blend", "blur", "doc", "fx", "group", "groupId", "h", "id", "link", "live", "morphId", "opacity", "role", "rotation", "shadow", "showOnHover", "themeRefs", "type", "url", "view", "w", "x", "y"],
      "code": ["align", "backdropFilter", "blend", "blur", "color", "content", "fontFamily", "fontSize", "fx", "grammarAssetId", "grammarName", "group", "groupId", "h", "id", "lineHeight", "link", "morphId", "opacity", "role", "rotation", "shadow", "showOnHover", "themeAssetId", "themeName", "themeRefs", "type", "valign", "w", "x", "y"],
    },
    "fx": ["ambient", "countUp", "enter", "enterDur", "ken", "loop", "order", "step"],
    "fxKen": ["dir", "duration", "scale"],
    "fxLoop": ["delay", "distance", "duration", "ease", "path", "speeds", "type"],
    "shadow": ["blur", "color", "x", "y"],
    "connectorEnd": ["el", "side"],
    "tableStyle": ["borderColor", "borderWidth", "cellPadX", "cellPadY", "color", "fontFamily", "fontSize", "headerBg", "headerColor", "radius", "zebra"],
    "tableRow": ["cells"],
    "tableCell": ["align", "bg", "bold", "color", "html"],
    "gradient": ["angle", "stops"],
    "imageCrop": ["scale", "x", "y"],
    "size": ["height", "width"],
    "meta": ["author", "company", "event", "keywords", "subject"],
    "theme": ["accent", "background", "chartPalette", "codePalette", "color", "fontFamily", "headingFamily", "palette", "table"],
    "themePalette": ["accent2", "accent3", "accent4", "accent5", "accent6", "bg2", "folHlink", "hlink", "tx2"],
    "themeCodePalette": ["a", "c", "d", "f", "k", "n", "p", "s"],
    "present": ["controls", "morphSeconds", "numberHidden", "progress", "slideNumber"],
    "font": ["asset", "family", "style", "weight"],
  } as const

export type ElementKind = keyof typeof MODEL_KEYS.element
